spring:
  data:
    mongodb:
      host: localhost
      port: 27012
      database: book-social-network
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

jwt:
  secretKey: 69f71e0d72868dc230c984f19d4330b59aecab6f8f98b58ec60cd58205275345
  expiresIn: 5h